aliases:
  - &run_cibuild
    - checkout
    - restore_cache:
        keys:
          - sbt-cache-{{ checksum "project/Versions.scala" }}
    - run:
        name: Executing cibuild
        command: ./scripts/test
    - save_cache:
        key: sbt-cache-{{ checksum "project/Versions.scala" }}
        paths:
          - "~/.ivy2/cache"
          - "~/.sbt"
          - "~/.cache/coursier"

  - &run_cipublish
    - checkout
    - restore_cache:
        keys:
          - sbt-cache-{{ checksum "project/Versions.scala" }}
    - run:
        name: "Import signing key"
        command: |
          echo "${GPG_KEY}" | base64 -d > signing_key.asc && \
          gpg --batch \
            --passphrase "${GPG_PASSPHRASE}" \
            --import signing_key.asc
    - run:
        name: Executing cipublish
        command: ./scripts/cipublish

  - &openjdk8-scala2_12_environment
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          # https://circleci.com/docs/2.0/java-oom/
          _JAVA_OPTIONS: "-Xms128m -Xmx2g"

version: 2
workflows:
  version: 2
  build:
    jobs:
      - "openjdk8-scala2.12":
          # required since openjdk8-scala2.12_deploy has tag filters AND requires
          # openjdk8-scala2.12
          # https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
          filters:
            tags:
              only:
                - /^(.*)$/
      - "openjdk8-scala2.12_deploy":
          context: sonatype-azavea-signing-key
          requires:
            - "openjdk8-scala2.12"
          filters:
            tags:
              only:
                - /^(.*)$/
            branches:
              ignore:
                - /^(.*)$/

jobs:
  "openjdk8-scala2.12":
    <<: *openjdk8-scala2_12_environment
    steps: *run_cibuild

  "openjdk8-scala2.12_deploy":
    <<: *openjdk8-scala2_12_environment
    steps: *run_cipublish
